import mongoose, { Schema } from "mongoose";
const courseSchema=new mongoose.Schema({
    courseTitle:({
        type:String,
        required:true
    }),
    subTitle:({
        type:String,
    }),
    coursePrice:({
        type:Number,
    }),
    courseDescription:({
        type:String,
    }),
    category:({
        type:String,
        required:true
    }),
    courseLevel:({
        type:String,
        enum:["Beginner","Medium","Easy"]
    }),
    courseImage:({
        type:String,
    }),
    enrolledStudents:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'User'
        }
    ],
    lectures:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'Lecture'
        }
    ],
    creator:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'User'
        }
    ],
    isPublished:
        {
            type:Boolean,
            default:false
        }
},{timestamps:true});

export const Course=mongoose.model("Course",courseSchema);